# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(170, 107)
        Form.setWindowOpacity(0.9)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(8, 8, 8, 8)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.work_button = PenetrateAnimatedButton(Form)
        self.work_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.work_button.setObjectName("work_button")
        self.gridLayout.addWidget(self.work_button, 0, 0, 1, 1)
        self.work_edit = PenetrateLineEdit(Form)
        self.work_edit.setStyleSheet("border: 2px solid gray;\n"
"padding: 6px;\n"
"border-radius: 10px;")
        self.work_edit.setText("")
        self.work_edit.setObjectName("work_edit")
        self.gridLayout.addWidget(self.work_edit, 0, 1, 1, 1)
        self.relax_button = PenetrateAnimatedButton(Form)
        self.relax_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.relax_button.setObjectName("relax_button")
        self.gridLayout.addWidget(self.relax_button, 1, 0, 1, 1)
        self.relax_edit = PenetrateLineEdit(Form)
        self.relax_edit.setStyleSheet("border: 2px solid gray;\n"
"padding: 6px;\n"
"border-radius: 10px;")
        self.relax_edit.setObjectName("relax_edit")
        self.gridLayout.addWidget(self.relax_edit, 1, 1, 1, 1)
        self.stop_button = PenetrateAnimatedButton(Form)
        self.stop_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stop_button.setObjectName("stop_button")
        self.gridLayout.addWidget(self.stop_button, 2, 0, 1, 1)
        self.clear_button = PenetrateAnimatedButton(Form)
        self.clear_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.clear_button.setObjectName("clear_button")
        self.gridLayout.addWidget(self.clear_button, 2, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.work_button.setText(_translate("Form", "PushButton"))
        self.relax_button.setText(_translate("Form", "PushButton"))
        self.stop_button.setText(_translate("Form", "PushButton"))
        self.clear_button.setText(_translate("Form", "PushButton"))
from customwidgets import PenetrateAnimatedButton, PenetrateLineEdit


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
